### PR TITLE
Update from beta to final babel 7

### PR DESCRIPTION
**Pull request by jrjohnson**
Trying to remove the message:

`warning "@ember/jquery > ember-cli-babel > babel-plugin-debug-macros@0.2.0" has unmet peer dependency "@babel/core@^7.0.0-beta.42"` 

from my ember app. Seemed easy enough that I could file a PR instead of an issue, but I might not have any idea what I'm doing here 😛

### CODE REVIEW

**Comment by rwjblue** [comment]
Ugh, will need a breaking change PR to drop Node 4 it looks like 😭

**Comment by rwjblue** [comment]
Ok, I think this should be passing with a rebase

**Comment by jrjohnson** [comment]
Rebased and indeed passing.

**Comment by jrjohnson** [comment]
Just a friendly bump on this, would love to see it in a release (though I know the breaking against a `0.2.0` is probably a bit fraught).

**Comment by Turbo87** [comment]
@jrjohnson released as `v0.3.0` now

**Pull request merged**
